### ISSUE TITLE
能够实现多个参数加密吗?  包含字符串 数字 特殊字符

### ISSUE THREAD

**Issue by eluotao** [ElfSundae/laravel-hashid#14]
比如('Sbds311',15613,'33')

这种能加密吗?

**Comment by ElfSundae** [comment]
不支持多参数，因为多参数可能会有不同的需求，而且有些 encoder 本身会把多参数当做数组处理。
你可以根据自己需要使用，比如加密前拼接原始串，或者挨个加密后拼接加密串。
