### ISSUE TITLE
Drop support for PHP 5.x, update hashids dependency to 3.x

### ISSUE THREAD

**Issue by vpratfr** [ElfSundae/laravel-hashid#16]
Considering that PHP 7.x is required since quite some time in Laravel, I think it is safe and sane to drop 5.x support.

This would allow to move on with some other dependencies such as hashids 3.x which requires PHP 7.x

**Comment by ElfSundae** [comment]
Thanks, it has been done in https://github.com/ElfSundae/laravel-hashid/pull/18
