### ISSUE TITLE
Laravel 8.0 Support

### ISSUE THREAD

**Issue by craftyshaun** [ElfSundae/laravel-hashid#24]
Hi;

I tried to upgrade to Laravel 8 today but noticed your package does not support this in the `composer.json`.

Is this something you'd like a PR for or are you happy to update the composer and tag a new release?

Cheers

Shaun

**Comment by ElfSundae** [comment]
Thanks for reminding me, just released 1.5.0 with L8 supported.

**Comment by craftyshaun** [comment]
Thanks for the update 🙏... One package closer to L8.
