### ISSUE TITLE
是否支持在laravel10中使用？

### ISSUE THREAD

**Issue by zhouzyc** [ElfSundae/laravel-hashid#30]
今天升级到laravel10后，无法安装
![image](https://github.com/ElfSundae/laravel-hashid/assets/18420689/8ce0aab4-2e7f-4fac-a4e5-1924ffd57a3a)

**Comment by ElfSundae** [comment]
@zhouzyc 已提交更新，请稍后再试下

**Comment by rhnkyr** [comment]
This one still an issue. Just tried today.
